export const CATEGORIES_IDS_TO_NAMES = {
    "31": "Anime/Animation",
    "40": "Sci-Fi/Fantasy",
    "22": "People & Blogs",
    "2": "Autos & Vehicles",
    "30": "Movies",
    "1": "Film & Animation",
    "21": "Videoblogging",
    "27": "Education",
    "10": "Music",
    "19": "Travel & Events",
    "15": "Pets & Animals",
    "39": "Horror",
    "36": "Drama",
    "32": "Action/Adventure",
    "43": "Shows",
    "17": "Sports",
    "37": "Family",
    "35": "Documentary",
    "42": "Shorts",
    "26": "Howto & Style",
    "18": "Short Movies",
    "24": "Entertainment",
    "28": "Science & Technology",
    "20": "Gaming",
    "38": "Foreign",
    "25": "News & Politics",
    "23": "Comedy",
    "29": "Nonprofits & Activism",
    "41": "Thriller",
    "44": "Trailers",
    "34": "Comedy",
    "33": "Classics",
};

export const CATEGORIES_NAMES_TO_IDS = {
    "Anime/Animation": ["31"],
    "Sci-Fi/Fantasy": ["40"],
    "People & Blogs": ["22"],
    "Autos & Vehicles": ["2"],
    Movies: ["30"],
    "Film & Animation": ["1"],
    Videoblogging: ["21"],
    Education: ["27"],
    Music: ["10"],
    "Travel & Events": ["19"],
    "Pets & Animals": ["15"],
    Horror: ["39"],
    Drama: ["36"],
    "Action/Adventure": ["32"],
    Shows: ["43"],
    Sports: ["17"],
    Family: ["37"],
    Documentary: ["35"],
    Shorts: ["42"],
    "Howto & Style": ["26"],
    "Short Movies": ["18"],
    Entertainment: ["24"],
    "Science & Technology": ["28"],
    Gaming: ["20"],
    Foreign: ["38"],
    "News & Politics": ["25"],
    Comedy: ["23", "34"],
    "Nonprofits & Activism": ["29"],
    Thriller: ["41"],
    Trailers: ["44"],
    Classics: ["33"],
};
